# Financial News Aggregator Configuration

# News Sources Configuration
sources:
  bloomberg:
    enabled: true
    rss_feeds:
      # Bloomberg RSS feeds focused on our target categories
      - "https://feeds.bloomberg.com/politics/news.rss"
      - "https://feeds.bloomberg.com/technology/news.rss"
      - "https://feeds.bloomberg.com/markets/news.rss"
    categories:
      - markets
      - technology
      - politics
      - finance
    max_articles_per_run: 15

  cnbc:
    enabled: true
    rss_feeds:
      # CNBC feeds for markets, tech, and politics
      - "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=20910258"  # Markets
      - "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910"  # Technology
      - "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000113"  # Politics
      - "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000115"  # Finance
    categories:
      - markets
      - technology
      - politics
      - finance
    max_articles_per_run: 15

  ft:
    enabled: true
    base_url: "https://www.ft.com"
    rss_feeds:
      - "https://www.ft.com/markets?format=rss"
      - "https://www.ft.com/technology?format=rss"
      - "https://www.ft.com/companies/financials?format=rss"
      - "https://www.ft.com/world/us/politics?format=rss"
    categories:
      - markets
      - technology
      - finance
      - politics
    max_articles_per_run: 15

  wsj:
    enabled: true
    rss_feeds:
      - "https://feeds.a.dj.com/rss/RSSMarketsMain.xml"
      - "https://feeds.a.dj.com/rss/RSSFinancialNews.xml"
      - "https://feeds.a.dj.com/rss/RSSPrivateEquity.xml"
      - "https://feeds.a.dj.com/rss/RSSCIO.xml"  # Tech/CIO Journal
    categories:
      - markets
      - finance
      - technology
      - private_equity
    max_articles_per_run: 15

  forbes:
    enabled: true
    rss_feeds:
      - "https://www.forbes.com/innovation/feed/"  # Tech & Innovation
      - "https://www.forbes.com/money/feed/"       # Finance & Money
      - "https://www.forbes.com/business/feed/"    # Business
      - "https://www.forbes.com/investing/feed/"   # Investing
    categories:
      - technology
      - finance
      - business
      - investing
    max_articles_per_run: 15

  economist:
    enabled: true
    rss_feeds:
      - "https://www.economist.com/finance-and-economics/rss.xml"  # Finance & Economics
      - "https://www.economist.com/business/rss.xml"               # Business
      - "https://www.economist.com/science-and-technology/rss.xml" # Technology
      - "https://www.economist.com/united-states/rss.xml"          # US Politics
      - "https://www.economist.com/international/rss.xml"          # International
      - "https://www.economist.com/leaders/rss.xml"                # Leaders/Opinion
      - "https://www.economist.com/briefing/rss.xml"               # Briefings
    categories:
      - finance
      - economics
      - politics
      - technology
      - business
      - international
    max_articles_per_run: 15

# Notification Settings
notifications:
  telegram:
    enabled: true
    format: "markdown"
    include_summary: true
    max_message_length: 4096

  slack:
    enabled: true
    format: "blocks"
    include_summary: true
    max_message_length: 3000

# Filtering Settings with targeted keywords
filters:
  # Minimum time between duplicate articles (in hours)
  duplicate_threshold_hours: 12
  
  # Similarity threshold for duplicate detection (0.0 to 1.0)
  # Articles with titles more similar than this are considered duplicates
  similarity_threshold: 0.75
  
  # Group similar stories from different sources
  group_similar_stories: true
  
  # Keywords to prioritize for our specific categories
  priority_keywords:
    # Market & Finance
    - "market"
    - "stocks"
    - "bonds"
    - "forex"
    - "trading"
    - "investment"
    - "IPO"
    - "merger"
    - "acquisition"
    - "earnings"
    - "federal reserve"
    - "interest rate"
    - "inflation"
    
    # Politics
    - "election"
    - "policy"
    - "regulation"
    - "legislation"
    - "congress"
    - "senate"
    - "government"
    - "political"
    
    # Crypto
    - "crypto"
    - "bitcoin"
    - "ethereum"
    - "blockchain"
    - "defi"
    - "NFT"
    - "cryptocurrency"
    - "digital asset"
    - "web3"
    
    # Tech & AI
    - "AI"
    - "artificial intelligence"
    - "machine learning"
    - "tech"
    - "software"
    - "startup"
    - "innovation"
    - "silicon valley"
    - "OpenAI"
    - "Google"
    - "Microsoft"
    - "Apple"
    - "Meta"
    
    # Aerospace & Defence
    - "aerospace"
    - "defense"
    - "defence"
    - "military"
    - "space"
    - "SpaceX"
    - "NASA"
    - "Boeing"
    - "Lockheed"
    - "satellite"
    - "rocket"
    
    # Private Equity
    - "private equity"
    - "venture capital"
    - "VC"
    - "PE"
    - "buyout"
    - "portfolio"
    - "fund"
    - "LBO"
    - "exit"
    
    # Breaking news
    - "breaking"
    - "urgent"
    - "exclusive"
    - "alert"
  
  # Keywords to exclude - remove irrelevant content
  exclude_keywords:
    - "sponsored"
    - "advertisement"
    - "promoted"
    - "lifestyle"
    - "entertainment"
    - "celebrity"
    - "fashion"
    - "travel"
    - "food"
    - "sports"
    - "gaming"
    - "real estate"

  # Required keywords - article must contain at least one
  required_keywords:
    - "market"
    - "finance"
    - "financial"
    - "politics"
    - "political"
    - "crypto"
    - "bitcoin"
    - "blockchain"
    - "AI"
    - "artificial intelligence"
    - "tech"
    - "technology"
    - "aerospace"
    - "defense"
    - "defence"
    - "space"
    - "private equity"
    - "venture capital"
    - "investment"
    - "trading"
    - "stocks"
    - "bonds"

# Schedule Settings
schedule:
  # Times in UTC - adjusted for market hours
  run_times:
    - "05:00"  # 5 AM UTC (Pre-market US)
    - "08:00"  # 8 AM UTC (European markets)
    - "13:00"  # 1 PM UTC (US market open)
    - "16:00"  # 4 PM UTC (Mid US trading)
    - "20:00"  # 8 PM UTC (US market close)
    - "23:00"  # 11 PM UTC (Asia pre-market)

# Storage Settings
storage:
  # Store processed article IDs to avoid duplicates
  history_file: "data/processed_articles.json"
  # Keep history for N days
  history_retention_days: 7

# Display Settings
display:
  # Maximum number of articles per notification
  max_articles_per_notification: 25
  # Include article preview
  include_preview: true
  # Preview length in characters
  preview_length: 200 