name: Financial News Aggregator

on:
  schedule:
    # Run at market-focused times (UTC)
    - cron: '0 5 * * *'   # 5 AM UTC (Pre-market US)
    - cron: '0 8 * * *'   # 8 AM UTC (European markets)
    - cron: '0 13 * * *'  # 1 PM UTC (US market open)
    - cron: '0 16 * * *'  # 4 PM UTC (Mid US trading)
    - cron: '0 20 * * *'  # 8 PM UTC (US market close)
    - cron: '0 23 * * *'  # 11 PM UTC (Asia pre-market)
  
  # Allow manual trigger
  workflow_dispatch:

# Add permissions for the workflow
permissions:
  contents: write

jobs:
  aggregate-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run news aggregator
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        BLOOMBERG_CREDENTIALS: ${{ secrets.BLOOMBERG_CREDENTIALS }}
        CNBC_CREDENTIALS: ${{ secrets.CNBC_CREDENTIALS }}
        FT_CREDENTIALS: ${{ secrets.FT_CREDENTIALS }}
        WSJ_CREDENTIALS: ${{ secrets.WSJ_CREDENTIALS }}
        FORBES_CREDENTIALS: ${{ secrets.FORBES_CREDENTIALS }}
      run: |
        python src/main.py
        
    - name: Commit processed articles history
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/processed_articles.json || true
        git diff --quiet && git diff --staged --quiet || git commit -m "Update processed articles history [skip ci]"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }} 